"""Fail-closed, activity-scoped zyBooks browser-control primitives."""

from .controller import (
    ActivityClassifier,
    ActivityKind,
    ActivityRecord,
    ActivityRoot,
    ActivityResources,
    CuaEnvironmentError,
    CuaPreflight,
    CuaResult,
    DiagnosticBundle,
    MutationDecision,
    MutationRequest,
    PageGenerationTracker,
    ProtectedContainerRegistry,
    RetryMachine,
    RetryState,
    TargetCandidate,
    TargetIdentity,
    TargetSelection,
    TargetSelectionStatus,
    TargetSelector,
    Telemetry,
    TransitionRecord,
    CheckpointJournal,
    OwnedObserver,
    OwnedTimer,
    TargetEvidence,
    graphical_environment_diagnostic,
    load_graphical_environment,
)
from .reconciliation import TargetReconciler, TargetReconciliation

__all__ = [
    "ActivityClassifier",
    "ActivityKind",
    "ActivityRecord",
    "ActivityRoot",
    "ActivityResources",
    "CheckpointJournal",
    "CuaEnvironmentError",
    "CuaPreflight",
    "CuaResult",
    "DiagnosticBundle",
    "MutationDecision",
    "MutationRequest",
    "OwnedObserver",
    "OwnedTimer",
    "PageGenerationTracker",
    "ProtectedContainerRegistry",
    "RetryMachine",
    "RetryState",
    "TargetCandidate",
    "TargetEvidence",
    "TargetIdentity",
    "TargetSelection",
    "TargetSelectionStatus",
    "TargetSelector",
    "TargetReconciler",
    "TargetReconciliation",
    "Telemetry",
    "TransitionRecord",
    "graphical_environment_diagnostic",
    "load_graphical_environment",
]
